# Generated by Django 4.2.2 on 2023-06-07 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mylist', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShoopingItem',
            new_name='ShopingItem',
        ),
    ]
